# Generated by Django 2.0.6 on 2019-11-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsterImage', models.URLField()),
                ('monsterHealthPoints', models.IntegerField()),
                ('monsterAttackPoints', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaponName', models.CharField(max_length=20)),
                ('shopHealthPoints', models.IntegerField()),
                ('shopAttackPoints', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=10, null=True)),
                ('userImage', models.URLField(blank=True, null=True)),
                ('healthPoints', models.IntegerField(blank=True, default=156, null=True)),
                ('attackPoints', models.IntegerField(blank=True, default=24, null=True)),
                ('weapon', models.CharField(max_length=40, null=True)),
                ('weaponAttack', models.IntegerField(blank=True, null=True)),
                ('weaponHealth', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
